//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://newv.com.cn/", ConfigurationName="ServiceReference2.UserInterfaceSoap")]
    public interface UserInterfaceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/GetUserInfoByLoginName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserInfoByLoginName(string callUserName, string callUserPassword, string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string loginName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Logout(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/Encrypto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApp.ServiceReference2.ReturnValue Encrypto(string callUserName, string callUserPassword, string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/InsertUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertUserInfo(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/UpdateUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateUserInfo(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/UpdateUserInfoByNull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateUserInfoByNull(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/DeleteUserByLoginName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteUserByLoginName(string callUserName, string callUserPassword, string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/CheckUserLoginName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckUserLoginName(string callUserName, string callUserPassword, string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/MoveDept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MoveDept(string callUserName, string callUserPassword, string oldDeptPath, string newDeptPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/SetDeptAcitve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetDeptAcitve(string callUserName, string callUserPassword, string deptPath, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/AddDept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddDept(string callUserName, string callUserPassword, string deptPath, bool isGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/RemoveUserFromUserGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RemoveUserFromUserGroup(string callUserName, string callUserPassword, string loginName, string fullGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newv.com.cn/InsertFolderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertFolderInfo(string folderCode, string folderName, string parentCode, string parentName, string remark);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://newv.com.cn/")]
    public partial class ReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hasErrorField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private object returnObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object ReturnObject {
            get {
                return this.returnObjectField;
            }
            set {
                this.returnObjectField = value;
                this.RaisePropertyChanged("ReturnObject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserInterfaceSoapChannel : WebApp.ServiceReference2.UserInterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserInterfaceSoapClient : System.ServiceModel.ClientBase<WebApp.ServiceReference2.UserInterfaceSoap>, WebApp.ServiceReference2.UserInterfaceSoap {
        
        public UserInterfaceSoapClient() {
        }
        
        public UserInterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserInterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetUserInfoByLoginName(string callUserName, string callUserPassword, string loginName) {
            return base.Channel.GetUserInfoByLoginName(callUserName, callUserPassword, loginName);
        }
        
        public string Login(string loginName, string password) {
            return base.Channel.Login(loginName, password);
        }
        
        public void Logout(string loginName) {
            base.Channel.Logout(loginName);
        }
        
        public WebApp.ServiceReference2.ReturnValue Encrypto(string callUserName, string callUserPassword, string str) {
            return base.Channel.Encrypto(callUserName, callUserPassword, str);
        }
        
        public string InsertUserInfo(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends) {
            return base.Channel.InsertUserInfo(callUserName, callUserPassword, loginName, password, userCode, realName, userStatusCode, leaderUserLoginName, sex, fullDeptName, fullUserGroupName, birthday, telephone, mobile, email, fieldValues, userExtends);
        }
        
        public string UpdateUserInfo(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends) {
            return base.Channel.UpdateUserInfo(callUserName, callUserPassword, loginName, password, userCode, realName, userStatusCode, leaderUserLoginName, sex, fullDeptName, fullUserGroupName, birthday, telephone, mobile, email, fieldValues, userExtends);
        }
        
        public string UpdateUserInfoByNull(
                    string callUserName, 
                    string callUserPassword, 
                    string loginName, 
                    string password, 
                    string userCode, 
                    string realName, 
                    string userStatusCode, 
                    string leaderUserLoginName, 
                    string sex, 
                    string fullDeptName, 
                    string fullUserGroupName, 
                    string birthday, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    string fieldValues, 
                    string userExtends) {
            return base.Channel.UpdateUserInfoByNull(callUserName, callUserPassword, loginName, password, userCode, realName, userStatusCode, leaderUserLoginName, sex, fullDeptName, fullUserGroupName, birthday, telephone, mobile, email, fieldValues, userExtends);
        }
        
        public bool DeleteUserByLoginName(string callUserName, string callUserPassword, string loginName) {
            return base.Channel.DeleteUserByLoginName(callUserName, callUserPassword, loginName);
        }
        
        public bool CheckUserLoginName(string callUserName, string callUserPassword, string loginName) {
            return base.Channel.CheckUserLoginName(callUserName, callUserPassword, loginName);
        }
        
        public string MoveDept(string callUserName, string callUserPassword, string oldDeptPath, string newDeptPath) {
            return base.Channel.MoveDept(callUserName, callUserPassword, oldDeptPath, newDeptPath);
        }
        
        public string SetDeptAcitve(string callUserName, string callUserPassword, string deptPath, bool isActive) {
            return base.Channel.SetDeptAcitve(callUserName, callUserPassword, deptPath, isActive);
        }
        
        public string AddDept(string callUserName, string callUserPassword, string deptPath, bool isGroup) {
            return base.Channel.AddDept(callUserName, callUserPassword, deptPath, isGroup);
        }
        
        public string RemoveUserFromUserGroup(string callUserName, string callUserPassword, string loginName, string fullGroupName) {
            return base.Channel.RemoveUserFromUserGroup(callUserName, callUserPassword, loginName, fullGroupName);
        }
        
        public string InsertFolderInfo(string folderCode, string folderName, string parentCode, string parentName, string remark) {
            return base.Channel.InsertFolderInfo(folderCode, folderName, parentCode, parentName, remark);
        }
    }
}
